### ISSUE TITLE
bug: R6查询无法解析rankName

### ISSUE THREAD

**Issue by strike94** [armoe-project/armoe-plugin#4]
[TRSSYz][10:39:45.626][ERRO] [R6战绩查询][r6s]
[TRSSYz][10:39:45.627][ERRO] TypeError: Cannot read properties of undefined (reading 'rankName')
    at r6s (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/armoe-plugin/apps/r6s.js:49:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/plugins/loader.js:283:52)

是必须要玩了当前赛季才不会报错吗，这个赛季没玩，返回的数据里没有currentSeasonBestRegion 这个字段
![image](https://user-images.githubusercontent.com/34638547/236594561-57583e66-f627-441d-9d8a-110330f87f42.png)

**Comment by RealHeart** [comment]
已修复
